[template]
src   = "riemann.config.tmpl"
dest  = "/opt/riemann/riemann.config"
owner = "root"
group = "root"
mode  = "0644"
#check_cmd = "$RIEMANN_PATH_CONF/riemann-$RIEMANN_VERSION/bin/riemann test /etc/confd/templates/riemann.config.tmpl"
check_cmd = "java -jar /root/riemann-syntax-check/target/riemann-syntax-check-0.2.4-standalone.jar /etc/confd/templates/riemann.config.tmpl"
reload_cmd = "/sbin/sv hub riemann"